# ひともじ config file
# Copyright (c) 2026 Hitomoji Project. All rights reserved.
# 先頭が # か ; の行はコメント行です。
# 各キーワードは大文字でも小文字でも使えます。
# Configファイルにエラーがある場合は、ログファイルに出力されます。
# ログファイルは、%APPDATA%\Hitomoji\ に保存されます。

[ui]
# バックスペースの動作：true=かな単位、false=アルファベット単位
backspace-unit-symbol=true
loglevel=info

[function-key]
# このセクションではキーに機能を割り当てられます。
# キー名＝機能名
# ・キー名には、モディファイアキー（SHIFT、CTRL、ALT）を指定できます。
# ・機能名には、下記のいずれかが指定できます。
# 同じキーに複数の機能を割り当てた場合、後勝ちになります。

# IMEのオンオフ切り替えキー（現状固定。変更不可）
# CTRL+SPACE=ime-toggle

# 見たまま確定キー
# ※変換中の文字列をそのまま確定します。
ENTER=finish

# 入力まま確定キー（半角／全角）
# ※入力したキーに戻して確定します。
TAB=finish-raw
SHIFT+TAB=finish-raw-wide

# ひらがな確定キー
ALT+ENTER=finish-hiragana

# カタカナ確定キー
SHIFT+ENTER=finish-katakana

# 入力取消キー
# ※変換中の文字をすべて消します。
ESC=cancel

# 変換キー(未実装)
# SPACE=conversion
# 再変換キー（未実装)
# CTRL+Z=cancel-finish

[key-table]
# ローマ字かな変換と同じ理屈で、記号類を登録できます。
# かなり大量に追加しても問題ないことを確認済みです
# 置換が不要な場合は、その行を削除してください。
# Configの再読み込みは、言語バーのメニュー「Reload Config」で行えます。

wi=うぃ
wwi=ゐ
we=うぇ
wwe=ゑ

@include layer2.sample.ini
