# このファイルは先回り置換のサンプルです。
# 利用者側で必要に応じて変更を加えてください。

[key-table]

<<=《
>>=》
[[=『
]]=』
|(=【
)|=】
->=→
<-=←


/o1=①
/o2=②

noma=々
/,,=〃
/*=※
/.=・
/y=〒

/bs=★
/ws=☆
/bo=●
/wo=○
/br=■
/wr=□
/bt=▲
/wt=△
/brr=◆
/orr=◇
/brt=▼
/wrt=▽
