# このファイルは先回り置換のサンプルです。
# 利用者側で必要に応じて変更を加えてください。

[key-table]

->=→
<-=←
<-=←
[[=『
]]=』
<<=《
>>=》
|(=【
)|=】

/.=・
/''=〃
/k=々
/y=〒
/*=※
/-=〜

+m=×
+/=÷

/s=☆
/r=□
/c=○
/t=△
/rr=◇
/rt=▽
/bs=★
/bc=●
/br=■
/bt=▲
/brr=◆
/brt=▼

/o1=①
/o2=②
/o3=③
/o4=④
/o5=⑤
/o6=⑥ 
/o7=⑦
/o8=⑧
/o9=⑨
/o10=⑩
/o11=⑪
/o12=⑫
/o13=⑬
/o14=⑭
/o15=⑮
/o16=⑯
/o17=⑰
/o18=⑱
/o19=⑲
/o20=⑳

/r1=Ⅰ
/r2=Ⅱ
/r3=Ⅲ
/r4=Ⅳ
/r5=Ⅴ
/r6=Ⅵ
/r7=Ⅶ
/r8=Ⅷ
/r9=Ⅸ
/r10=Ⅹ
/r11=Ⅺ
/r12=Ⅻ

/alpha=α
/beta=β
/gamma=γ
/delta=δ
/epsilon=ε
/zeta=ζ
/eta=η
/theta=θ
/iota=ι
/kappa=κ
/lambda=λ
/mu=μ
/nu=ν
/omicron=ο
/xsi=ξ
/phi=φ
/ro=ρ
/chi=χ
/psi=ψ
/sigma=σ
/tau=τ
/upsilon=υ
/omega=ω
